version: '3.3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Expose Node.js backend on port 5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "7000:80"  # Expose Nginx on port 3000